# This workflow uses actions that are not certified by GitHub.  They are
# provided by a third-party and are governed by separate terms of service,
# privacy policy, and support documentation.
#
# This workflow will install a prebuilt Ruby version, install dependencies, and
# run tests and linters.
name: "Ruby on Rails CI"
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      # Add or replace dependency steps here
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf # v1.146.0
        with:
          ruby-version: 3.1.2 # Specify the Ruby version you want to use
          bundler-cache: true
      # Add or replace database setup steps here
      - name: Set up database schema
        run: |
          chmod +x bin/rails
          bin/rails db:schema:load
      # Add or replace test runners here
      # - name: Run tests
      #   run: |
      #     chmod +x bin/rake
      #     bin/rake

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf # v1.146.0
        with:
          ruby-version: 3.1.2 # Specify the Ruby version you want to use
          bundler-cache: true
  
  deploy:
    needs: [test, lint] # Only run this job if the test and lint jobs pass
    runs-on: ubuntu-latest
    steps:
      - name: Create deployment package
        run: |
          zip -r myapp.zip . -i .
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Upload deployment package to S3
        run: |
          aws s3 cp myapp.zip s3://elasticbeanstalk-us-east-1-225574881592
      - name: Deploy to AWS Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v14
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: todotest # Replace with the name of your Elastic Beanstalk application
          environment_name: Todotest-env # Replace with the name of your Elastic Beanstalk environment
          version_label: ${{ github.sha }}
          deployment_package: myapp.zip
          use_existing_version_if_available: false
          region: us-east-1 # Replace with the AWS region where your Elastic Beanstalk environment is located
